env:
  OPERATOR_VERSION: "1.0.2"

steps:
  - label: ":wrench: Build Buildkite Image"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/docker-build-buildkite-plugin#v4.0.0:
          docker_compose_file: "docker-compose.yml"
          docker_image: "cached-certificate-operator"
          tag: "$OPERATOR_VERSION"
          namespace: "infra-cached-certificate-operator"
          env: "buildkite"

  - label: ":wrench: Build Labs Image"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/docker-build-buildkite-plugin#v4.0.0:
          docker_compose_file: "docker-compose.yml"
          docker_image: "cached-certificate-operator"
          tag: "$OPERATOR_VERSION"
          namespace: "infra-cached-certificate-operator"
          env: "labs"

  - label: ":wrench: Build Labs-Staging Image"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/docker-build-buildkite-plugin#v4.0.0:
          docker_compose_file: "docker-compose.yml"
          docker_image: "cached-certificate-operator"
          tag: "$OPERATOR_VERSION"
          namespace: "infra-cached-certificate-operator"
          env: "labs-staging"

  - label: ":wrench: Build Staging Image"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/docker-build-buildkite-plugin#v4.0.0:
          docker_compose_file: "docker-compose.yml"
          docker_image: "cached-certificate-operator"
          tag: "$OPERATOR_VERSION"
          namespace: "infra-cached-certificate-operator"
          env: "staging"

  - label: ":wrench: Build Prod Image"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/docker-build-buildkite-plugin#v4.0.0:
          docker_compose_file: "docker-compose.yml"
          docker_image: "cached-certificate-operator"
          tag: "$OPERATOR_VERSION"
          namespace: "infra-cached-certificate-operator"
          env: "production"

  - wait

  - label: ":rocket: Deploy to Buildkite"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.buildkite.yaml"
          env: "buildkite"
          cluster: "buildkite"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Labs [Cluster=Labs]"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.labs.yaml"
          env: "labs"
          cluster: "labs"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Labs [Cluster=Modeling]"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.labs.yaml"
          env: "labs"
          cluster: "modeling"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Labs-Staging"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.labs-staging.yaml"
          env: "labs-staging"
          cluster: "labs-staging"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Staging"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.staging.yaml"
          env: "staging"
          cluster: "deployment"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Production [Cluster=Flyte]"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.production.yaml"
          env: "production"
          cluster: "flyte"
          wait_for_rollout: true

  - label: ":rocket: Deploy to Production [Cluster=Deployment]"
    branches: "main"
    plugins:
      - ssh://git@github.com/pachama/helm-deploy-buildkite-plugin#v4.0.0:
          k8s_file: "k8s-files/k8s.production.yaml"
          env: "production"
          cluster: "deployment"
          wait_for_rollout: true
