# permissions for end users to edit cachedcertificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cachedcertificate-editor-role
rules:
- apiGroups:
  - cache.weavelab.xyz
  resources:
  - cachedcertificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.weavelab.xyz
  resources:
  - cachedcertificates/status
  verbs:
  - get
