apiVersion: cache.weavelab.xyz/v1alpha1
kind: CachedCertificate
metadata:
  name: cachedcertificate-sample
spec:
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - example.com
