## Append samples you want in your CSV to this file as resources ##
resources:
- cache_v1alpha1_cachedcertificate.yaml
- cache_v1alpha1_cachedcertificate-2.yaml
- cache_v1alpha1_cachedcertificate-alt.yaml
- cache_v1alpha1_cachedcertificate-alt-2.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
